on:
  pull_request:
    branches:
      - develop
      - master

name: Pull request checks

jobs:
  check:
    name: pull-request-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run build
      run: npm run build
    - name: Run tests
      run: npm run test